# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [9]:
import torch

random_tensor = torch.rand(7, 7, device='cuda')
print(random_tensor)

tensor([[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967, 0.4150],
        [0.8203, 0.2290, 0.9096, 0.1183, 0.0752, 0.4092, 0.9601],
        [0.2093, 0.1940, 0.8909, 0.4387, 0.3570, 0.5454, 0.8299],
        [0.2099, 0.7684, 0.4290, 0.2117, 0.6606, 0.1654, 0.4250],
        [0.9927, 0.6964, 0.2472, 0.7028, 0.7494, 0.9303, 0.0494],
        [0.0750, 0.7223, 0.9478, 0.3647, 0.2215, 0.7784, 0.6391],
        [0.2077, 0.7045, 0.9609, 0.0594, 0.3358, 0.0616, 0.7030]],
       device='cuda:0')


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
random_tensor_1 = torch.rand(1, 7, device='cuda')

y = random_tensor @ random_tensor_1.T
print(y)


tensor([[2.1205],
        [1.5476],
        [1.2218],
        [1.7224],
        [2.4212],
        [1.3042],
        [1.4658]], device='cuda:0')


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
torch.manual_seed(0)

random_tensor_2 = torch.rand(7, 7)
random_tensor_3 = torch.rand(1, 7)

y_1 = random_tensor_2 @ random_tensor_3.T
print(y_1)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    torch.cuda.manual_seed_all(1234)
random_tensor_4 = torch.rand(2, 3, device='cuda')
random_tensor_5 = torch.rand(2, 3, device='cuda')
print(random_tensor_4, random_tensor_5)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [29]:
y_2=random_tensor_4 @ random_tensor_5.T
print(y_2)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [30]:
max= y_2.max()
print(max)

min=y_2.min()
print(min)


tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
argmax= y_2.argmax()
print(argmax)

argmin=y_2.argmin()
print(argmin)


tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [34]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(7)
    torch.cuda.manual_seed_all(7)
random_tensor_6 = torch.rand(1, 1, 1, 10, device='cuda')
print("Shape:", random_tensor_6.shape)
print(random_tensor_6)

squeezed_tensor = random_tensor_6.squeeze()
print(squeezed_tensor)
print("New shape:", squeezed_tensor.shape)


Shape: torch.Size([1, 1, 1, 10])
tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0')
tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')
New shape: torch.Size([10])
